In [3]:
import Pkg
Pkg.add(["Random","LinearAlgebra"])

    Updating registry at `~/.julia/registries/JuliaComputingRegistry.toml`
    Updating registry at `~/.julia/registries/JuliaHubRegistry.toml`
   Resolving package versions...
    Updating `~/Documents/programming/BME-574-2024/Project.toml`
  [37e2e46d] + LinearAlgebra
  [9a3f8284] + Random
  No Changes to `~/Documents/programming/BME-574-2024/Manifest.toml`
Precompiling project...
  ✓ StaticArrayInterface
  ✓ StaticArrayInterface → StaticArrayInterfaceStaticArraysExt
  ✓ StaticArrayInterface → StaticArrayInterfaceOffsetArraysExt
  ✓ CloseOpenIntervals
  ✓ LayoutPointers
  ✓ TiledIteration
  ✓ VectorizationBase
  ✓ SLEEFPirates
  ✓ LoopVectorization
  ✓ LoopVectorization → SpecialFunctionsExt
  ✓ LoopVectorization → ForwardDiffExt
  ✓ ImageMorphology
  ✓ ImageDistances
  ✓ Plots
  ✓ Plots → FileIOExt
  ✓ ImageFiltering
  ✓ Plots → UnitfulExt
  ✓ ImageSegmentation
  ✓ ImageCorners
  ✓ ImageQualityIndexes
  ✓ Images
  21 dependencies successfully precompiled in 32 seconds. 350 already p

In [5]:
using Random, LinearAlgebra

In [8]:
a = rand(3,4)

3×4 Matrix{Float64}:
 0.31288    0.0437718  0.421157  0.712074
 0.841569   0.714041   0.11609   0.674368
 0.0887607  0.577726   0.191507  0.746344

In [9]:
vec(a)

12-element Vector{Float64}:
 0.3128804751045914
 0.8415693013917479
 0.08876069488692795
 0.04377183464078349
 0.7140411312727882
 0.5777260716789111
 0.42115731862569283
 0.11608959245213335
 0.19150718791367438
 0.7120744541616485
 0.6743681880230896
 0.7463435355607879

In [10]:
vec(a')

12-element reshape(adjoint(::Matrix{Float64}), 12) with eltype Float64:
 0.3128804751045914
 0.04377183464078349
 0.42115731862569283
 0.7120744541616485
 0.8415693013917479
 0.7140411312727882
 0.11608959245213335
 0.6743681880230896
 0.08876069488692795
 0.5777260716789111
 0.19150718791367438
 0.7463435355607879

In [11]:
a

3×4 Matrix{Float64}:
 0.31288    0.0437718  0.421157  0.712074
 0.841569   0.714041   0.11609   0.674368
 0.0887607  0.577726   0.191507  0.746344

In [12]:
a'

4×3 adjoint(::Matrix{Float64}) with eltype Float64:
 0.31288    0.841569  0.0887607
 0.0437718  0.714041  0.577726
 0.421157   0.11609   0.191507
 0.712074   0.674368  0.746344

In [13]:
a * a'

3×3 Matrix{Float64}:
 0.784234  0.823658  0.665166
 0.823658  1.68634   1.01276
 0.665166  1.01276   0.93535

In [14]:
a' * a

4×4 Matrix{Float64}:
 0.814012  0.66589   0.246468  0.856568
 0.66589   0.845538  0.211966  0.943878
 0.246468  0.211966  0.227525  0.521113
 0.856568  0.943878  0.521113  1.51885