In [1]:
import Pkg
Pkg.activate(".")

  Activating project at `~/Documents/programming/BME-574-2024`


In [2]:
using LinearAlgebra, Random

In [3]:
x = rand(5,3)

5×3 Matrix{Float64}:
 0.886299  0.662609  0.823187
 0.405924  0.117705  0.274987
 0.385112  0.313621  0.186609
 0.590693  0.45849   0.462369
 0.92451   0.315961  0.872233

In [4]:
u,s,v = svd(x, full = true)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
5×5 Matrix{Float64}:
 -0.626571  -0.334143   0.502927    -0.36354    -0.332657
 -0.224898   0.222949  -0.59463      0.0355229  -0.738152
 -0.230064  -0.443647  -0.621794    -0.436551    0.415985
 -0.397037  -0.383979  -0.082213     0.822125    0.110785
 -0.58844    0.703121  -0.00967648  -0.0105105   0.398942
singular values:
3-element Vector{Float64}:
 2.1919214593873653
 0.3234432473917768
 0.1306713598127307
Vt factor:
3×3 Matrix{Float64}:
 -0.690612  -0.402276  -0.601023
  0.144461  -0.891014   0.430378
 -0.708651   0.2104     0.673458

In [13]:
u * u'

5×5 Matrix{Float64}:
 1.0           1.72584e-16  1.76204e-16   2.6965e-16   9.57773e-17
 1.72584e-16   1.0          1.9043e-17   -1.00871e-16  1.83932e-16
 1.76204e-16   1.9043e-17   1.0           2.5655e-16   6.79937e-17
 2.6965e-16   -1.00871e-16  2.5655e-16    1.0          3.94483e-17
 9.57773e-17   1.83932e-16  6.79937e-17   3.94483e-17  1.0

In [14]:
v * v'

3×3 Matrix{Float64}:
  1.0          -8.32667e-17  -2.42861e-16
 -8.32667e-17   1.0          -1.66533e-16
 -2.42861e-16  -1.66533e-16   1.0

In [11]:
u * Diagonal(s) * v'

5×3 Matrix{Float64}:
 0.144979  0.251267  0.535139
 0.886284  0.378973  0.390439
 0.368925  0.731688  0.588375
 0.366569  0.676477  0.84237
 0.336813  0.151192  0.150847

In [25]:
Diagonal(s)

3×3 Diagonal{Float64, Vector{Float64}}:
 1.87086   ⋅         ⋅ 
  ⋅       0.614108   ⋅ 
  ⋅        ⋅        0.230488

In [26]:
zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [23]:
vcat(Diagonal(s),zeros(2,3))

5×3 Matrix{Float64}:
 1.87086  0.0       0.0
 0.0      0.614108  0.0
 0.0      0.0       0.230488
 0.0      0.0       0.0
 0.0      0.0       0.0

In [24]:
u * vcat(Diagonal(s),zeros(2,3)) * v' ≈ x

true