In [1]:
import Pkg
Pkg.activate(".")

  Activating project at `~/Documents/programming/BME-574-2024`


In [2]:
using LinearAlgebra, Random

In [3]:
x = rand(5,3)

5×3 Matrix{Float64}:
 0.144979  0.251267  0.535139
 0.886284  0.378973  0.390439
 0.368925  0.731688  0.588375
 0.366569  0.676477  0.84237
 0.336813  0.151192  0.150847

In [12]:
u,s,v = svd(x, full = true)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
5×5 Matrix{Float64}:
 -0.299385  -0.293684   0.676028   -0.603117   -0.057918
 -0.491928   0.787313   0.121675    0.0307949  -0.349846
 -0.526762  -0.230511  -0.705034   -0.41083    -0.0594308
 -0.595649  -0.392622   0.173977    0.674777    0.0738853
 -0.189998   0.294281   0.0289904  -0.105816    0.930195
singular values:
3-element Vector{Float64}:
 1.8708647213421679
 0.6141076210030586
 0.23048785822375245
Vt factor:
3×3 Matrix{Float64}:
 -0.51103    -0.576604  -0.637476
  0.855482   -0.268996  -0.442484
  0.0836601  -0.771472   0.630739

In [13]:
u * u'

5×5 Matrix{Float64}:
 1.0           1.72584e-16  1.76204e-16   2.6965e-16   9.57773e-17
 1.72584e-16   1.0          1.9043e-17   -1.00871e-16  1.83932e-16
 1.76204e-16   1.9043e-17   1.0           2.5655e-16   6.79937e-17
 2.6965e-16   -1.00871e-16  2.5655e-16    1.0          3.94483e-17
 9.57773e-17   1.83932e-16  6.79937e-17   3.94483e-17  1.0

In [14]:
v * v'

3×3 Matrix{Float64}:
  1.0          -8.32667e-17  -2.42861e-16
 -8.32667e-17   1.0          -1.66533e-16
 -2.42861e-16  -1.66533e-16   1.0

In [11]:
u * Diagonal(s) * v'

5×3 Matrix{Float64}:
 0.144979  0.251267  0.535139
 0.886284  0.378973  0.390439
 0.368925  0.731688  0.588375
 0.366569  0.676477  0.84237
 0.336813  0.151192  0.150847

In [25]:
Diagonal(s)

3×3 Diagonal{Float64, Vector{Float64}}:
 1.87086   ⋅         ⋅ 
  ⋅       0.614108   ⋅ 
  ⋅        ⋅        0.230488

In [26]:
zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [23]:
vcat(Diagonal(s),zeros(2,3))

5×3 Matrix{Float64}:
 1.87086  0.0       0.0
 0.0      0.614108  0.0
 0.0      0.0       0.230488
 0.0      0.0       0.0
 0.0      0.0       0.0

In [24]:
u * vcat(Diagonal(s),zeros(2,3)) * v' ≈ x

true